fragment AssetFragment on Asset {
  attributeId
  createdAt
  data
  id
  mimeType
  name
  processingStatus
  resourceId
  size
  storageProviderId
  updatedAt
  uploadStatus
  uploaderId
  url
  workspaceId
}
