query FetchProductVariantReleaseRule($input: FetchProductVariantReleaseRuleInput!) {
  productVariantReleaseRule: fetchProductVariantReleaseRule(input: $input) {
    id
    productVariantId
    minimumReleaseId
    recommendedReleaseId
    latestReleaseId
    autoRecommendNewReleases
    createdAt
    updatedAt

    minimumRelease {
      ...ProductVariantReleaseFragment
    }

    recommendedRelease {
      ...ProductVariantReleaseFragment
    }

    latestRelease {
      ...ProductVariantReleaseFragment
    }
  }
}
