fragment ItemFragment on Item {
  id
  name
  identifier
  description
  createdAt
  updatedAt
  pricings {
    id
    kind
    amount
    originalAmount
    isRecurring
    recurringInterval
    recurringIntervalUnit
    appleProductIdentifier
    googleProductIdentifier
    currencyCode
    createdAt
    updatedAt
  }
}
