query LoadInAppChatAgent($identityId: UUID!) {
  loadInAppChatAgent(input: { identityId: $identityId }) {
    id
    name
    avatar
    starterMessages
    starterSuggestions
    showStarterSuggestionLabel
  }
}
